import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Web3 from "web3";
import ConnectButton from "../components/Button/ConnectButton";
import { useWeb3Context } from "../components/web3Context";
import styles from "../styles/Home.module.css";

const initWeb3 = (provider: any) => {
  const web3: any = new Web3(provider);
  web3.eth.extend({
    methods: [
      {
        name: "chainId",
        call: "eth_chainId",
        outputFormatter: web3.utils.hexToNumber,
      },
    ],
  });
  return web3;
};

const Home: NextPage = () => {
  const [connected, setConnected] = useState(false);
  const { connect, address } = useWeb3Context();

  useEffect(() => {
    console.log(address);
  }, [address]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {address ? (
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://beoble.io">Beoble!</a>
          </h1>

          <p className={styles.description}>
            your address is <code className={styles.code}>{address}</code>
          </p>
        </main>
      ) : (
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://beoble.io">Beoble!</a>
          </h1>

          <p className={styles.description}>
            Get started by adding{" "}
            <code className={styles.code}>kits/Chat.tsx</code>
          </p>
          <ConnectButton onClick={connect} />
        </main>
      )}

      <footer className={styles.footer}>
        <a href="https://beoble.io" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/beoble_horizontal_black.png"
              alt="Vercel Logo"
              width={72}
              height={28.61}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
